services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shrinkitwebv2
    restart: unless-stopped
    networks:
      - caddy
    labels:
      caddy: shrinkit.rihosting.com.br
      caddy.reverse_proxy: "{{upstreams 3000}}"
    ports:
      - "3000:3000"

networks:
  caddy:
    external: true
